import {finishPhoto} from './photo-finish.mjs';
import {suggestTone} from './auto-tone.mjs';
import {openSamples} from './sample-gallery.mjs';
import {CAMERA_COPY,FILM_COPY} from './original-copy.mjs';
import {defaultFilmSettings,readFilmSettings,saveFilmSettings} from './film-settings.mjs';
import {EDIT_DEFAULTS} from './editor-settings.mjs';
import {CONTROL_KEYS,divisor,labelValue,mountEditorUI} from './editor-ui.mjs';
import {FINISH_DEFAULTS,prepareFinish,finishImage} from './finish.mjs';
import {mountVideo} from './video.mjs';
import {Renderer,Assets} from './renderer.mjs';
import {canvasBlob,download,zip,outputName} from './export.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base=p=>new URL(p,import.meta.url).href;const tick=()=>new Promise(r=>setTimeout(r,0));
let editorUI,videoUI,mistBypass=false;
let D,artwork,libraryMode='artwork',assets,renderer,photo,preset,settings,view='single',zoom='fit',family='全部',renderId=0,thumbId=0,gridId=0,exporting=false,cancelExport=false,timer,toastTimer,previewImage;
const thumbnailCache=new Map();const defaultSettings=defaultFilmSettings;
const launch=new URLSearchParams(location.search);const embedded=launch.get('embedded')==='1';
if(embedded)document.body.classList.add('embedded-editor');
const tellParent=message=>{if(embedded)parent.postMessage(message,location.origin);};
function status(s){$('#status').textContent=s;}function error(e){console.error(e);$('#toast').textContent=e.message||String(e);$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,9000);status('处理失败：'+(e.message||e));$('#loading').hidden=true;}
function controls(){for(const key of CONTROL_KEYS){const el=$('#'+key),value=settings[key]??0;if(!el)continue;el.value=value*divisor(key);$('#'+key+'-value').textContent=labelValue(key,value);const f=(Number(el.value)-Number(el.min))/(Number(el.max)-Number(el.min))*100;el.style.background=`linear-gradient(to right,#b9c99e ${f}%,#4a533f ${f}%)`;}editorUI?.refresh();}
async function autoWhiteBalance(){try{const originalPhoto=photo,originalPreset=preset;const im=await assets.image(originalPhoto.preview),c=document.createElement('canvas');c.width=96;c.height=96;const x=c.getContext('2d');x.drawImage(im,0,0,96,96);const d=x.getImageData(0,0,96,96).data,sums=[0,0,0];let n=0;for(let i=0;i<d.length;i+=4){const rgb=[d[i],d[i+1],d[i+2]],hi=Math.max(...rgb),lo=Math.min(...rgb);if(hi>70&&hi<245&&hi-lo<65){rgb.forEach((v,k)=>sums[k]+=v);n++;}}if(n<20){status('未找到足够的中性区域，请手动调整色温与色调。');return;}if(exporting||photo!==originalPhoto||preset!==originalPreset)return;const [r,g,b]=sums.map(v=>v/n/255),clamp=x=>Math.min(1,Math.max(-1,x));settings.temperature=clamp(Math.log((b+.01)/(r+.01))/.36);settings.tint=clamp(Math.log((g+.01)/(Math.sqrt(r*b)+.01))/.12);controls();requestRender();}catch(e){error(e);}}

async function autoTone(){try{const ph=photo,p=preset;const im=await assets.image(ph.preview);if(photo!==ph||preset!==p||exporting)return;const c=document.createElement('canvas');c.width=128;c.height=128;const x=c.getContext('2d');x.drawImage(im,0,0,128,128);const patch=suggestTone(x.getImageData(0,0,128,128).data);if(!patch){status('画面层次不足，请手动调节。');return;}Object.assign(settings,patch);controls();requestRender();}catch(e){error(e);}}

function visiblePresets(){const q=$('#search').value.trim().toLowerCase();return D.presets.filter(p=>p.group==='main'&&(family==='全部'||p.family===family)&&(p.name+' '+p.id).toLowerCase().includes(q));}
function filterList(){
 const list=visiblePresets();$('#filter-count').textContent=list.length;
 $('#filters').dataset.mode=libraryMode;
 $('#filters').innerHTML=list.map((p,i)=>{
  const art=artwork.presets[p.id],original=libraryMode==='artwork'&&art;
  return `<button class="filter-card ${p.id===preset.id?'active':''}" data-preset="${p.id}" aria-label="选择 ${escape(p.name)}" title="${escape(original?art.mapping:'当前 before 的滤镜效果预览')}"><img src="${base(original?art.src:photo.thumb)}" alt="${escape(p.name)} ${original?'原包卡片':'效果预览'}" ${original?`data-asset="${art.assetName}"`:''}><span class="filter-name">${escape(p.name.split(' · ').slice(1).join(' · '))}<i>${p.id===preset.id?'●':String(i+1).padStart(2,'0')}</i></span><small>${original?(art.shared?'50D 系列共用卡片':p.family+' · 原包卡片'):'效果预览'}</small></button>`;
 }).join('')||'<p class="export-note">没有匹配的胶片</p>';
 $('#filters').querySelectorAll('button').forEach(b=>b.onclick=()=>selectPreset(b.dataset.preset));
 if(libraryMode==='preview')makeThumbnails(list);else ++thumbId;
}

async function thumbnail(p,ph,s=defaultSettings(p),width=260){const key=[p.id,ph.id,JSON.stringify(s),width,s.dateFollowSystem?Math.floor(Date.now()/60000):''].join('|');if(thumbnailCache.has(key))return thumbnailCache.get(key);const [im,prepared]=await Promise.all([assets.image(ph.preview),assets.prepare(p,s.node,s.kelvin)]);const h=Math.round(width*ph.height/ph.width);renderer.render(im,prepared,s,width,h,[ph.width,ph.height]);const finished=await finishPhoto(renderer.canvas,s,{renderer,assets,preset:p,photos:D.photos});const url=finished.toDataURL('image/jpeg',.91);thumbnailCache.set(key,url);if(thumbnailCache.size>160)thumbnailCache.delete(thumbnailCache.keys().next().value);return url;}
async function makeThumbnails(list){const id=++thumbId,ph=photo;for(const p of list){if(id!==thumbId)return;try{const src=await thumbnail(p,ph,defaultSettings(p),170);if(id!==thumbId)return;const img=$(`#filters [data-preset="${p.id}"] img`);if(img){img.src=src;img.dataset.rendered='true';}}catch(e){error(e);return;}await tick();}}
function photoList(){ $('.header-note').innerHTML='<i></i> 本地处理 · '+D.photos.length+' 张 before · 31 款主预设';$('#photo-count').textContent=D.photos.length+' 张';$('[data-view=photos]').textContent='这款的 '+D.photos.length+' 张';$('#export-batch').textContent='导出这款的 '+D.photos.length+' 张 ZIP';$('#photos').innerHTML=D.photos.map((p,i)=>`<button class="${p.id===photo.id?'active':''}" data-photo="${p.id}" aria-label="选择原图 ${i+1}：${escape(p.name)}" title="${escape(p.name)}"><img src="${base(p.thumb)}" alt="before ${i+1}" loading="lazy"><span>${String(i+1).padStart(2,'0')}</span></button>`).join('');$('#photos').querySelectorAll('button').forEach(b=>b.onclick=()=>selectPhoto(b.dataset.photo));}
function selectPhoto(id){if(exporting)return;photo=D.photos.find(p=>p.id===id);photoList();filterList();requestRender();}
function selectPreset(id){if(exporting)return;const p=D.presets.find(p=>p.id===id);if(!p?.available||p.group!=='main')return;preset=p;settings=readFilmSettings(p);controls();filterList();requestRender();}
function fit(){if(!photo)return;$('#preview-area').classList.toggle('zoomed',zoom==='pixel'&&view==='single');if(zoom==='pixel'){const stage=$('#photo-stage');stage.style.width=($('#result').width||photo.width)+'px';stage.style.height=($('#result').height||photo.height)+'px';return;}const outer=$('#single-view');const padding=innerWidth<850?18:34;const w=outer.clientWidth-padding,h=outer.clientHeight-padding;if(w<=0||h<=0)return;const rw=$('#result').width||photo.width,rh=$('#result').height||photo.height;const scale=Math.min(w/rw,h/rh);$('#photo-stage').style.width=Math.max(1,Math.round(rw*scale))+'px';$('#photo-stage').style.height=Math.max(1,Math.round(rh*scale))+'px';}
function requestRender(){if(exporting)return;mistBypass=false;refreshMistCompare();saveFilmSettings(preset,settings);tellParent({type:'gloam:selection',name:preset.name});updateProfile();clearTimeout(timer);const id=++renderId;++gridId;timer=setTimeout(()=>render(id).catch(error),35);}
async function render(id){const ph=photo,p=preset,s={...settings,...(mistBypass?{blackMistGrade:0}:{})};$('#effect-title').textContent=p.name;$('#open-camera').href='camera.html?preset='+encodeURIComponent(p.id);const art=artwork.presets[p.id];$('#selected-artwork').hidden=!art;if(art){$('#selected-artwork').src=base(art.src);$('#selected-artwork').alt=p.name+' 原包卡片';$('#selected-artwork').title=art.mapping;}$('#family-label').textContent=p.family;$('#matrix-controls').hidden=p.kind!=='matrix';$('#preset-desc').textContent=p.kind==='matrix'?'矩阵色表 · 颗粒与光学质感\n近似复刻，待原片校准。':'原始 Cube 色表 · 本地质感配方\n近似复刻，待原片校准。';$('#evidence-text').textContent=p.kind==='matrix'?'采用原包 PNG 矩阵，按 33³、R 最快行序读取并插值。装载与颜色域仍待原 App 对照；质感强度为本地设定。':'采用原包 33³ Cube。黑柔与光晕使用恢复的原版内核、档位；浏览器模糊及色彩处理仍需原 App 同图校准。';$('#evidence-link').href=p.evidence;$('#image-info').textContent=`${D.photos.indexOf(ph)+1} / ${D.photos.length} · ${ph.width} × ${ph.height} · 近似复刻`;$('#loading').hidden=false;
 const [im,prepared]=await Promise.all([assets.image(ph.full),assets.prepare(p,s.node,s.kelvin)]);if(id!==renderId)return;previewImage=im;const scale=zoom==='pixel'?1:Math.min(1,1400/Math.max(ph.width,ph.height)),w=Math.round(ph.width*scale),h=Math.round(ph.height*scale);const start=performance.now();renderer.render(im,prepared,s,w,h,[ph.width,ph.height]);const canvas=$('#result');const finished=await finishPhoto(renderer.canvas,s,{renderer,assets,preset:p,photos:D.photos});if(id!==renderId)return;canvas.width=finished.width;canvas.height=finished.height;canvas.getContext('2d').drawImage(finished,0,0);$('#image-info').textContent=`${D.photos.indexOf(ph)+1} / ${D.photos.length} · 输出 ${finished.width} × ${finished.height} · 近似复刻`;$('#before').style.objectPosition=`${s.cropX*100}% ${s.cropY*100}%`;$('#before').src=im.src;const paired=p.family==='G-HALF'&&s.collageLayout!=='none';$('#compare').disabled=paired;$('#hold').disabled=paired;if(paired){$('#photo-stage').classList.remove('split','holding');$('#compare').setAttribute('aria-pressed','false');}$('#result').dataset.preset=p.id;$('#result').dataset.photo=ph.id;$('#result').dataset.amount=String(s.amount);$('#result').dataset.settings=JSON.stringify(s);$('#result').dataset.zoom=zoom;$('#result').dataset.mistBypass=String(mistBypass);$('#loading').hidden=true;$('#export').disabled=false;$('#export-batch').disabled=false;fit();status(`${mistBypass?'仅关闭黑柔对比 · ':''}${p.name} · ${zoom==='pixel'?'100% 原图细节，可滚动查看':'适应窗口'} · 预览 ${finished.width} × ${finished.height} · 按需渲染 ${Math.round(performance.now()-start)} ms · 导出按原始像素处理`);if(view!=='single')await buildGrid();}
async function buildGrid(){const id=++gridId,ph=photo,p=preset,s={...settings},v=view;$('#contact-grid').innerHTML='';$('#loading').textContent='正在生成对照缩略图…';$('#loading').hidden=false;const items=v==='filters'?[{original:true,photo:ph},...visiblePresets().map(p=>({preset:p,photo:ph,settings:p.id===preset.id?s:defaultSettings(p)}))]:D.photos.map(photo=>({preset:p,photo,settings:s}));
 for(let i=0;i<items.length;i++){if(id!==gridId||v!==view)return;const item=items[i],src=item.original?base(item.photo.preview):await thumbnail(item.preset,item.photo,item.settings,320);if(id!==gridId||v!==view)return;const b=document.createElement('button');b.className='contact-card'+(item.preset?.id===preset.id&&item.photo.id===photo.id?' active':'');b.innerHTML=`<img src="${src}" alt="${escape(item.original?'原图':item.preset.name+' · before '+item.photo.id)}"><span>${escape(item.original?'原图 · BEFORE':v==='photos'?'BEFORE '+String(D.photos.indexOf(item.photo)+1).padStart(2,'0'):item.preset.name)}</span><small>${item.original?'未应用滤镜':v==='photos'?`${item.photo.width} × ${item.photo.height}`:item.preset.id===preset.id?'当前参数':'默认试片配方'}</small>`;b.onclick=()=>{if(item.original){setView('single');$('#compare').click();return;}view='single';updateView();if(v==='photos')selectPhoto(item.photo.id);else selectPreset(item.preset.id);};$('#contact-grid').append(b);status(`正在生成 ${i+1} / ${items.length} 张对照预览`);await tick();}
 if(id===gridId){$('#loading').hidden=true;status(`${items.length} 张对照图已就绪 · 点击任一照片进入单张预览`);}}
function updateView(){for(const b of $$('[data-view]'))b.classList.toggle('active',b.dataset.view===view);$('#single-view').hidden=view!=='single';$('#contact-grid').hidden=view==='single';$('#zoom').hidden=view!=='single';$('#hold').hidden=view!=='single';$('#compare').hidden=view!=='single';$('#export-sheet').hidden=view==='single';fit();}
function setView(v){view=v;updateView();requestRender();}
function exportLock(on){exporting=on;tellParent({type:'gloam:busy',busy:on});if(on){++thumbId;++gridId;++renderId;clearTimeout(timer);}$('#cancel-export').hidden=!on;for(const b of $$('button,input,select'))if(b.id!=='cancel-export'&&b.id!=='open-video'&&!b.closest('#video-editor'))b.disabled=on;if(!on)refreshMistCompare();}
async function exportOne(){const p=preset,ph=photo,s={...settings};exportLock(true);try{status('正在渲染原尺寸 PNG…');const [im,prepared]=await Promise.all([assets.image(ph.full),assets.prepare(p,s.node,s.kelvin)]);renderer.render(im,prepared,s,ph.width,ph.height,[ph.width,ph.height]);const out=await finishPhoto(renderer.canvas,s,{renderer,assets,preset:p,photos:D.photos}),blob=await canvasBlob(out);download(blob,outputName(ph,p,s.amount));status(`已导出 ${out.width} × ${out.height} PNG · ${(blob.size/1024/1024).toFixed(1)} MB`);}catch(e){error(e);}finally{exportLock(false);requestRender();}}
async function exportBatch(){const p=preset,s={...settings};exportLock(true);cancelExport=false;const files=[];try{const prepared=await assets.prepare(p,s.node,s.kelvin);for(let i=0;i<D.photos.length;i++){if(cancelExport){status('导出已停止，未生成不完整 ZIP。');return;}const ph=D.photos[i];status(`正在导出 ${i+1} / ${D.photos.length}：${p.name} · ${ph.width} × ${ph.height}`);await tick();const im=await assets.image(ph.full);renderer.render(im,prepared,s,ph.width,ph.height,[ph.width,ph.height]);files.push({name:outputName(ph,p,s.amount),blob:await canvasBlob(await finishPhoto(renderer.canvas,s,{renderer,assets,preset:p,photos:D.photos}))});await tick();}if(cancelExport){status('导出已停止');return;}files.push({name:'试片参数.json',blob:new Blob([JSON.stringify({preset:p.id,settings:s,scope:'近似复刻，未与原 App 同图校准',sources:D.photos.map(({id,name,sha256})=>({id,name,sha256}))},null,2)],{type:'application/json'})});status('正在打包 ZIP…');const blob=await zip(files);download(blob,`Gloam_${p.id}_${D.photos.length}张_${Math.round(s.amount*100)}%.zip`);status(`已导出 ${D.photos.length} 张 PNG + 参数记录 · ${(blob.size/1024/1024).toFixed(1)} MB`);}catch(e){error(e);}finally{exportLock(false);requestRender();}}
async function exportSheet(){if($('#loading').hidden===false)return;const cards=$$('#contact-grid .contact-card'),cols=4,w=300,h=438;const canvas=document.createElement('canvas');canvas.width=cols*w;canvas.height=Math.ceil(cards.length/cols)*h+70;const c=canvas.getContext('2d');c.fillStyle='#1b2016';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='#dce5ce';c.font='22px sans-serif';c.fillText(`Gloam · ${view==='filters'?'全部滤镜 / BEFORE '+photo.id:preset.name+' / 14 张'} · 近似复刻`,20,43);for(let i=0;i<cards.length;i++){const im=cards[i].querySelector('img');await im.decode();const x=i%cols*w,y=Math.floor(i/cols)*h+70,sc=Math.min((w-24)/im.naturalWidth,380/im.naturalHeight),iw=im.naturalWidth*sc,ih=im.naturalHeight*sc;c.drawImage(im,x+(w-iw)/2,y+(380-ih)/2,iw,ih);c.font='14px sans-serif';c.fillText(cards[i].querySelector('span').textContent,x+12,y+404);}download(await canvasBlob(canvas),'Gloam_对照图.png');status('已导出滤镜对照图');}
function hold(on){$('#photo-stage').classList.toggle('holding',on&&view==='single');}
async function init(){const response=await fetch(base('manifest.json'));if(!response.ok)throw Error('滤镜清单加载失败');D=await response.json();const ar=await fetch(base('artwork.json'));if(!ar.ok)throw Error('原包卡片清单加载失败');artwork=await ar.json();assets=new Assets(D);renderer=new Renderer(document.createElement('canvas'));photo=D.photos.find(p=>p.id===launch.get('photo'))||D.photos[0];preset=D.presets.find(p=>p.id===launch.get('preset')&&p.available&&p.group==='main')||D.presets[0];settings=readFilmSettings(preset);editorUI=mountEditorUI({getPreset:()=>preset,getSettings:()=>settings,onChange:patch=>{Object.assign(settings,patch);controls();requestRender();},onAutoWB:autoWhiteBalance,onAutoTone:autoTone,getPhotos:()=>D.photos});mountMistCompare();await prepareFinish();videoUI=mountVideo({manifest:D,getPreset:()=>preset,getSettings:()=>({...settings})});$('#families').innerHTML=['全部',...new Set(D.presets.filter(p=>p.group==='main').map(p=>p.family))].map(f=>`<button data-family="${escape(f)}" class="${f==='全部'?'active':''}">${artwork.families[f]?`<img src="${base(artwork.families[f].src)}" alt="" width="28" height="24">`:""}<span>${escape(f)}</span></button>`).join('');$('#families').querySelectorAll('button').forEach(b=>b.onclick=()=>{family=b.dataset.family;$('#families').querySelectorAll('button').forEach(a=>a.classList.toggle('active',a===b));filterList();if(view==='filters')requestRender();});$$('[data-library-mode]').forEach(b=>b.onclick=()=>{libraryMode=b.dataset.libraryMode;$$('[data-library-mode]').forEach(a=>a.setAttribute('aria-pressed',String(a===b)));filterList();});$('#search').oninput=()=>{filterList();if(view==='filters')requestRender();};photoList();controls();filterList();
 for(const key of CONTROL_KEYS)$('#'+key).oninput=e=>{settings[key]=Number(e.target.value)/divisor(key);controls();requestRender();};
 $('#zoom').onclick=()=>{zoom=zoom==='fit'?'pixel':'fit';$('#zoom').setAttribute('aria-pressed',String(zoom==='pixel'));$('#zoom').textContent=zoom==='pixel'?'适应窗口':'100% 细节';fit();requestRender();};$('#reset').onclick=()=>{settings=defaultSettings(preset);controls();requestRender();};$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#compare').onclick=()=>{const on=$('#compare').getAttribute('aria-pressed')!=='true';$('#compare').setAttribute('aria-pressed',String(on));$('#photo-stage').classList.toggle('split',on);};$('#split-position').oninput=e=>{const v=e.target.value;$('#before').style.clipPath=`inset(0 ${100-v}% 0 0)`;$('#divider').style.left=v+'%';};$('#hold').onpointerdown=e=>{e.preventDefault();$('#hold').setPointerCapture(e.pointerId);hold(true);};$('#hold').onpointerup=()=>hold(false);$('#hold').onpointercancel=()=>hold(false);window.addEventListener('blur',()=>hold(false));document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|BUTTON|SELECT/.test(e.target.tagName)||exporting)return;if(e.code==='Space'){e.preventDefault();hold(true);}if(e.key==='ArrowRight')$('#next').click();if(e.key==='ArrowLeft')$('#prev').click();});document.addEventListener('keyup',e=>{if(e.code==='Space')hold(false);});$('#prev').onclick=()=>selectPhoto(D.photos[(D.photos.indexOf(photo)+D.photos.length-1)%D.photos.length].id);$('#next').onclick=()=>selectPhoto(D.photos[(D.photos.indexOf(photo)+1)%D.photos.length].id);$('#export').onclick=exportOne;$('#export-batch').onclick=exportBatch;$('#export-sheet').onclick=()=>exportSheet().catch(error);$('#cancel-export').onclick=()=>cancelExport=true;new ResizeObserver(fit).observe($('#preview-area'));if(embedded)$('.wordmark').onclick=e=>{e.preventDefault();if(!exporting)tellParent({type:'gloam:close'});};requestRender();tellParent({type:'gloam:ready'});}
function refreshMistCompare(){const hint=$('#mist-camera-note');if(hint&&preset)hint.textContent=preset.family==='GRD'?'GRD 默认开启；初始 1/8 档暂定，待原 App 默认档位确认。':'此相机默认关闭黑柔；手动开启属于本地试片扩展。';const b=$('#mist-compare');if(!b)return;b.disabled=exporting||!(settings?.blackMistGrade>0)||!(settings?.amount>0);b.setAttribute('aria-pressed',String(mistBypass));b.textContent=mistBypass?'返回当前黑柔效果':'仅关闭黑柔对比';}
function mountMistCompare(){
 const row=$('#blackMistGrade').closest('.range-control');
 const boost=document.createElement('div');boost.className='mist-boost';boost.innerHTML='<label for="blackMistBoost">可见度增强 · 本地<output id="blackMistBoost-value">0%</output></label><input id="blackMistBoost" type="range" min="0" max="100" step="1" value="0">';row.append(boost);
 const b=document.createElement('button');b.id='mist-compare';b.type='button';row.append(b);
 const policyNote=document.createElement('p');policyNote.id='mist-camera-note';policyNote.className='mist-note';row.append(policyNote);
 const note=document.createElement('p');note.className='mist-note';note.textContent='增强会扩大高光扩散并加强柔化；调到 0% 恢复原包档位基准。黑柔关闭时，增强也不生效。';row.append(note);
 b.onclick=()=>{if(exporting||!(settings.blackMistGrade>0)||!(settings.amount>0))return;mistBypass=!mistBypass;view='single';updateView();refreshMistCompare();clearTimeout(timer);render(++renderId).catch(error);};refreshMistCompare();
}
function updateProfile(){
 if(!artwork)return;
 let profile=$('#film-profile');if(!profile){profile=document.createElement('section');profile.id='film-profile';profile.setAttribute('aria-label','当前胶片配置卡片');$('.preset-caption').before(profile);}
 const art=artwork.presets[preset.id],siblings=D.presets.filter(p=>p.group==='main'&&p.family===preset.family);
 if(preset.family==='U2'){const order=['U2_XTRA400','U2_C1002','U2_U400V2','U2_Gold200'];siblings.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));}
 const signature=preset.id;if(profile.dataset.preset===signature)return;profile.dataset.preset=signature;
 profile.innerHTML=`<div class="camera-description"><div class="camera-heading">${artwork.families[preset.family]?`<img src="${base(artwork.families[preset.family].src)}" alt="">`:''}<strong>${escape(preset.family)}</strong>${preset.family==='U2'?'<span>晴天 · 闪光灯</span>':''}<button class="camera-samples" type="button" aria-label="查看 ${escape(preset.family)} 原 App 样片">样片 ↗</button></div><p>${escape(CAMERA_COPY[preset.family]?.description||'')}</p><small>原 App 相机介绍</small></div>${art?`<img class="profile-art" src="${base(art.src)}" alt="${escape(preset.name)} 原包卡片">`:''}<div class="profile-heading"><strong>${escape(preset.name)}</strong><small>${art?.shared?'50D 系列共用卡片':'原包胶片卡片'} · 本机独立配置</small></div><div class="sibling-films" style="--film-count:${Math.min(4,siblings.length)}" aria-label="同相机胶片">${siblings.map(p=>`<button data-sibling="${p.id}" aria-label="切换到 ${escape(p.name)}" aria-pressed="${p.id===preset.id}">${artwork.presets[p.id]?`<img src="${base(artwork.presets[p.id].src)}" alt="">`:''}<span>${escape(p.name.split(' · ').slice(1).join(' · '))}</span></button>`).join('')}</div><p class="film-summary">${escape(FILM_COPY[preset.id]?.summary||'')}${FILM_COPY[preset.id]?.shared?'<small>同系列说明</small>':''}</p>`;
 profile.querySelector('.camera-samples').onclick=()=>openSamples(preset.family,preset.id);
 profile.querySelectorAll('[data-sibling]').forEach(b=>b.onclick=()=>selectPreset(b.dataset.sibling));
}
window.addEventListener('message',e=>{
 if(!embedded||e.origin!==location.origin||e.source!==parent||!D||exporting||e.data?.type!=='gloam:photos')return;
 for(const ph of e.data.photos||[])if(typeof ph.id==='string'&&ph.id.startsWith('upload-')&&typeof ph.full==='string'&&ph.full.startsWith('blob:')&&!D.photos.some(p=>p.id===ph.id))D.photos.push(ph);
 const next=D.photos.find(p=>p.id===e.data.selected);if(next){photo=next;photoList();filterList();requestRender();}
});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&embedded&&!exporting&&!document.querySelector('#video-editor:not([hidden])')){e.preventDefault();tellParent({type:'gloam:close'});}});
init().catch(error);
