import {Renderer,Assets} from './renderer.mjs?v=20260921-live-measured-1';
import {finishImage,prepareFinish} from './finish.mjs?v=20260921-live-measured-1';

// A separate renderer keeps moving video textures out of the photo renderer cache.
export function mountVideo({manifest,getPreset,getSettings}) {
 const link=document.createElement('link');link.rel='stylesheet';link.href=new URL('./video.css',import.meta.url);document.head.append(link);
 const open=document.createElement('button');open.id='open-video';open.textContent='本地视频';(document.querySelector('.viewer-toolbar')||document.body).append(open);
 const panel=document.createElement('section');panel.id='video-editor';panel.hidden=true;panel.setAttribute('aria-label','本地视频显影');
 panel.innerHTML=`<header><div><h2>视频显影</h2><small>本地处理 · 使用当前胶片与显影参数</small></div><button data-action="close" aria-label="关闭视频显影">×</button></header>
 <div class="video-import"><label class="video-file">选择本地视频<input id="video-file" type="file" accept="video/*"></label><span data-role="name">尚未载入视频</span><button data-action="clear" disabled>清除</button></div>
 <div class="video-pair"><figure><video id="video-source" playsinline preload="metadata"></video><figcaption>原片</figcaption></figure><figure><canvas id="video-result" width="1" height="1"></canvas><figcaption>显影结果 <span data-role="preset"></span></figcaption></figure></div>
 <div class="video-transport"><button data-action="play" disabled>播放</button><input id="video-seek" type="range" min="0" max="1" step="0.01" value="0" aria-label="视频播放位置" disabled><output data-role="time">0:00 / 0:00</output></div>
 <div class="video-export"><label>尺寸<select id="video-size"><option value="1280">长边 1280px</option><option value="native">原片尺寸（最大 4096px）</option></select></label><label>声音<select id="video-audio"><option value="preserve">保留原片声音</option><option value="silent">无音轨（主动移除声音）</option></select></label><button data-action="export" disabled>导出视频</button><button data-action="cancel" hidden>取消导出</button><a data-role="download" hidden>下载成片</a></div>
 <progress data-role="progress" max="1" value="0" hidden></progress><p data-role="status" role="status" aria-live="polite">选择本地视频后，可在右侧调整参数。导出按片长实时录制，保持页面可见。</p><p class="video-note">视频为单画面处理，不使用照片半格拼图。浏览器重编码 · 最高 30fps · 格式依浏览器支持选用 WebM / MP4。输出与原 App 编码、HDR、音频通道及逐帧精度不同；滤镜效果仍需原 App 对照校准。</p>`;
 document.body.append(panel);
 const $=s=>panel.querySelector(s),action=n=>$(`[data-action="${n}"]`),role=n=>$(`[data-role="${n}"]`),video=$('video'),canvas=$('canvas'),seek=$('#video-seek'),fileInput=$('#video-file');
 let loadEpoch=0,duration=0;
 let renderer,assets,sourceURL,downloadURL,currentFile,ready=false,snapshot,prepared,preparation=0,frameId,frameKind,starting=false,recording=false,recorder,stream,stopExport,disposed=false,context,sourceNode,audioDestination,exportWidth,exportHeight;
 const status=s=>role('status').textContent=s;
 const fail=e=>{console.error(e);status('处理失败：'+(e.message||e));};
 const stamp=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
 function setReady(on){ready=on;for(const n of ['play','clear','export'])action(n).disabled=!on;seek.disabled=!on;}
 function cancelFrame(){if(frameId!==undefined){if(frameKind==='video')video.cancelVideoFrameCallback(frameId);else cancelAnimationFrame(frameId);frameId=undefined;}}
 function dimensions(max){const ratio=Math.min(1,max/Math.max(video.videoWidth,video.videoHeight));return [Math.max(2,Math.floor(video.videoWidth*ratio/2)*2),Math.max(2,Math.floor(video.videoHeight*ratio/2)*2)];}
 function draw(){if(!ready||!prepared||video.readyState<2)return;const [w,h]=recording?[exportWidth,exportHeight]:dimensions(960);renderer.lastImages.source=null;renderer.render(video,prepared,snapshot.settings,w,h,[video.videoWidth,video.videoHeight]);finishImage(renderer.canvas,snapshot.settings,canvas);canvas.dataset.frames=String(Number(canvas.dataset.frames||0)+1);canvas.dataset.preset=snapshot.preset.id;seek.value=video.currentTime;role('time').textContent=`${stamp(video.currentTime)} / ${stamp(duration)}`;if(recording){role('progress').value=video.currentTime/duration;status(`正在导出 ${Math.round(video.currentTime/duration*100)}% · ${stamp(video.currentTime)} / ${stamp(duration)} · ${snapshot.preset.name}`);}}
 function schedule(){cancelFrame();if(video.paused||video.ended||panel.hidden||!ready)return;const next=()=>{frameId=undefined;try{draw();schedule();}catch(e){video.pause();if(recording)stopExport?.(e);else fail(e);}};if(video.requestVideoFrameCallback){frameKind='video';frameId=video.requestVideoFrameCallback(next);}else{frameKind='animation';frameId=requestAnimationFrame(next);}}
 async function refresh(){if(!ready||recording||panel.hidden||disposed)return;const id=++preparation,preset=getPreset(),settings={...getSettings()};const next=await assets.prepare(preset,settings.node,settings.kelvin);if(id!==preparation||recording||!ready)return;prepared=next;snapshot={preset,settings};role('preset').textContent=preset.name;draw();}
 function releaseDownload(){if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=null;role('download').hidden=true;role('download').removeAttribute('href');}
 function clear(){if(recording)return;loadEpoch++;preparation++;video.pause();cancelFrame();video.removeAttribute('src');video.load();if(sourceURL)URL.revokeObjectURL(sourceURL);sourceURL=null;currentFile=null;prepared=null;setReady(false);canvas.width=canvas.height=1;fileInput.value='';role('name').textContent='尚未载入视频';role('time').textContent='0:00 / 0:00';seek.value=0;releaseDownload();status('已清除本地视频。');}
 const waitEvent=(target,event,timeout=15000)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>done(Error('等待视频超时，请尝试其他格式。')),timeout);function done(error){clearTimeout(timer);target.removeEventListener(event,ok);target.removeEventListener('error',bad);error?reject(error):resolve();}function ok(){done();}function bad(){done(Error('浏览器无法解码此视频。'));}target.addEventListener(event,ok,{once:true});target.addEventListener('error',bad,{once:true});});
 async function load(file){if(recording)throw Error('请先取消正在进行的导出。');clear();if(!file)return;const epoch=loadEpoch;panel.hidden=false;status('正在读取本地视频…');try{renderer??=new Renderer(document.createElement('canvas'));assets??=new Assets(manifest);await prepareFinish();if(epoch!==loadEpoch||disposed)return;currentFile=file;sourceURL=URL.createObjectURL(file);const loaded=waitEvent(video,'loadeddata');video.src=sourceURL;video.load();await loaded;if(epoch!==loadEpoch||disposed)return;duration=video.duration;if(!Number.isFinite(duration)){const end=waitEvent(video,'seeked');video.currentTime=1e10;await end;duration=Number.isFinite(video.duration)?video.duration:video.currentTime;const start=waitEvent(video,'seeked');video.currentTime=0;await start;}if(!Number.isFinite(duration)||duration<=0||duration>=1e10)throw Error('此视频缺少有效时长，无法安全导出。请先转存为标准 MP4 / WebM。');if(!video.videoWidth||!video.videoHeight)throw Error('视频没有可解码的画面。');/* loadeddata can precede a GPU-uploadable first frame. Force decode, then restore exact start. */if(video.currentTime===0){const decode=waitEvent(video,'seeked');video.currentTime=Math.min(.001,duration/2);await decode;const rewind=waitEvent(video,'seeked');video.currentTime=0;await rewind;}if(epoch!==loadEpoch||disposed)return;seek.max=duration;setReady(true);role('name').textContent=`${file.name} · ${video.videoWidth} × ${video.videoHeight} · ${stamp(duration)}`;await refresh();status('视频已就绪。播放预览，或在右侧调整显影参数。');}catch(e){if(epoch!==loadEpoch||disposed)return;clear();fail(e);throw e;}}
 async function audioTrack(){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('浏览器不支持声音合成；可主动选择“无音轨”后导出。');context??=new Audio();if(!sourceNode){sourceNode=context.createMediaElementSource(video);audioDestination=context.createMediaStreamDestination();sourceNode.connect(audioDestination);sourceNode.connect(context.destination);}await context.resume();if(context.state!=='running')throw Error('声音通道未启动，请重试，或选择“无音轨”。');const track=audioDestination.stream.getAudioTracks()[0];if(!track||track.readyState!=='live')throw Error('声音轨道不可用；可主动选择“无音轨”后导出。');return track.clone();}
 function lock(on){recording=on;for(const el of panel.querySelectorAll('button,input,select'))el.disabled=on;action('cancel').disabled=false;action('cancel').hidden=!on;role('progress').hidden=!on;if(!on){action('close').disabled=false;setReady(ready);}}
 async function exportVideo(){if(!ready||recording||starting)return;starting=true;for(const el of panel.querySelectorAll('button,input,select'))el.disabled=true;video.pause();cancelFrame();let timer,chunks=[],failure,cancelled=false,track;try{if(!window.MediaRecorder||!canvas.captureStream)throw Error('当前浏览器不支持视频导出。');await refresh();const preserve=$('#video-audio').value==='preserve';if(preserve)track=await audioTrack();const type=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/webm','video/mp4'].find(t=>MediaRecorder.isTypeSupported(t));if(!type)throw Error('当前浏览器没有可用的视频编码器。');[exportWidth,exportHeight]=dimensions(Math.min(renderer.maxSize,$('#video-size').value==='native'?4096:1280));lock(true);releaseDownload();if(video.currentTime!==0){const sought=waitEvent(video,'seeked');video.currentTime=0;await sought;}draw();stream=canvas.captureStream(30);if(track)stream.addTrack(track);recorder=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:8000000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};const done=new Promise(resolve=>{recorder.onstop=resolve;recorder.onerror=e=>{failure=e.error||Error('编码失败');if(recorder.state!=='inactive')recorder.stop();else resolve();};});stopExport=e=>{if(e)failure=e;else cancelled=true;video.pause();cancelFrame();if(recorder.state!=='inactive')recorder.stop();};recorder.start(1000);timer=setTimeout(()=>stopExport(Error('导出超时，已停止。请保持页面可见并尝试较短视频。')),(duration+30)*1000);await video.play();schedule();await done;if(failure)throw failure;if(cancelled){status('已取消导出，未生成不完整成片。');return;}const blob=new Blob(chunks,{type:recorder.mimeType});if(!blob.size)throw Error('编码器未输出视频数据。');downloadURL=URL.createObjectURL(blob);const a=role('download');a.href=downloadURL;a.download=`Gloam_${currentFile.name.replace(/\.[^.]+$/,'')}_${snapshot.preset.id}${preserve?'':'_无音轨'}.${recorder.mimeType.includes('mp4')?'mp4':'webm'}`;a.hidden=false;a.textContent=`下载成片 · ${(blob.size/1048576).toFixed(1)} MB`;panel.dataset.exported=String(blob.size);panel.dataset.audio=preserve?'preserved':'silent';status(`导出完成 · ${canvas.width} × ${canvas.height} · ${preserve?'已接入原片音频（原片无声时保留静音）':'无音轨'} · 点击“下载成片”保存。`);}catch(e){fail(e);}finally{clearTimeout(timer);video.pause();cancelFrame();if(recorder?.state!=='inactive')recorder?.stop();stream?.getTracks().forEach(t=>t.stop());track?.stop();stream=null;recorder=null;stopExport=null;starting=false;lock(false);}}
 fileInput.addEventListener('change',()=>load(fileInput.files[0]).catch(()=>{}));
 open.onclick=()=>{panel.hidden=false;refresh().catch(fail);};action('close').onclick=()=>{if(recording)return;video.pause();panel.hidden=true;cancelFrame();};action('clear').onclick=clear;
 action('play').onclick=async()=>{try{if(video.paused){await refresh();if(video.ended)video.currentTime=0;await context?.resume();await video.play();}else video.pause();}catch(e){fail(e);}};
 action('export').onclick=exportVideo;action('cancel').onclick=()=>stopExport?.();
 video.addEventListener('play',()=>{action('play').textContent='暂停';schedule();});video.addEventListener('pause',()=>{action('play').textContent='播放';cancelFrame();});video.addEventListener('seeked',()=>{try{draw();}catch(e){fail(e);}});
 video.addEventListener('ended',()=>{cancelFrame();if(recording&&recorder?.state!=='inactive'){draw();recorder.stop();}});
 video.addEventListener('error',()=>{if(ready){const e=Error('视频解码中断，请换用浏览器支持的文件。');if(recording)stopExport?.(e);else{video.pause();fail(e);}}});
 seek.oninput=()=>{if(!recording&&ready)video.currentTime=Number(seek.value);};
 let refreshTimer;const change=e=>{if(panel.contains(e.target)||e.target===open)return;clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(fail),70);};document.addEventListener('input',change);document.addEventListener('change',change);document.addEventListener('click',change);
 const visibility=()=>{if(document.hidden){if(recording)stopExport?.(Error('页面已进入后台，导出已停止；请保持页面可见重试。'));else video.pause();}};document.addEventListener('visibilitychange',visibility);
 return {load,refresh,exportVideo,clear,panel,video,canvas,destroy(){if(recording){stopExport?.();return;}disposed=true;clear();clearTimeout(refreshTimer);context?.close();renderer?.gl.getExtension('WEBGL_lose_context')?.loseContext();for(const event of ['input','change','click'])document.removeEventListener(event,change);document.removeEventListener('visibilitychange',visibility);panel.remove();open.remove();link.remove();}};
}
